---
title: "'Catch' non può trovarsi dopo 'Finally' in un'istruzione 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ab300d332dd82870901aec9bd57d8d5d8081a533
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403771"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' non può trovarsi dopo 'Finally' in un'istruzione 'Try'
Nel codice un'istruzione `Catch` figura dopo l'istruzione `Finally` che termina un blocco di istruzioni `Try` . `Catch` deve figurare all'interno di un blocco di istruzioni `Try...Catch...Finally` .  
  
 **ID errore:** BC30379  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1. Spostare l'istruzione `Catch` in una posizione più appropriata nel codice.  
  
## <a name="see-also"></a>Vedere anche

- [Istruzione Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
