---
title: "Blocco 'Catch' non raggiunto. <exception> gestito sopra nella stessa istruzione 'Try' "
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395480"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Blocco 'Catch' non raggiunto. \<exception> gestito sopra nella stessa istruzione 'Try' 
Un blocco `Catch` nel codice non è raggiungibile perché è gestito in un blocco `Try` precedente.  
  
Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID errore:** BC42031  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
- Rimuovere l'istruzione ridondante.  
  
## <a name="see-also"></a>Vedere anche

- [Come usare il blocco try/catch per rilevare le eccezioni](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Utilizzo di gestori eccezioni filtrati dall'utente](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Istruzione Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
