---
ms.openlocfilehash: 52406f1e4ea4eda417909e52cf6529631cb0ae33
ms.sourcegitcommit: e02d17b2cf9c1258dadda4810a5e6072a0089aee
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 07/01/2020
ms.locfileid: "85620221"
---
### <a name="change-in-behavior-for-taskwaitall-methods-with-time-out-arguments"></a><span data-ttu-id="2ae15-101">Modifica del comportamento per i metodi Task.WaitAll con argomenti di timeout</span><span class="sxs-lookup"><span data-stu-id="2ae15-101">Change in behavior for Task.WaitAll methods with time-out arguments</span></span>

#### <a name="details"></a><span data-ttu-id="2ae15-102">Dettagli</span><span class="sxs-lookup"><span data-stu-id="2ae15-102">Details</span></span>

<span data-ttu-id="2ae15-103">In .NET Framework 4.5 il comportamento di <xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> è stato reso più coerente. In .NET Framework 4 questi metodi avevano un comportamento non coerente.</span><span class="sxs-lookup"><span data-stu-id="2ae15-103"><xref:System.Threading.Tasks.Task.WaitAll%2A?displayProperty=nameWithType> behavior was made more consistent in .NET Framework 4.5.In the .NET Framework 4, these methods behaved inconsistently.</span></span> <span data-ttu-id="2ae15-104">Alla scadenza del timeout, se una o più attività sono state completate o annullate prima della chiamata al metodo, il metodo genera un'eccezione <xref:System.AggregateException?displayProperty=fullName>.</span><span class="sxs-lookup"><span data-stu-id="2ae15-104">When the time-out expired, if one or more tasks were completed or canceled before the method call, the method threw an <xref:System.AggregateException?displayProperty=fullName> exception.</span></span> <span data-ttu-id="2ae15-105">Alla scadenza del timeout, se nessuna attività è stata completata o annullata prima della chiamata al metodo, ma una o più attività sono entrate in questi stati dopo la chiamata al metodo, il metodo restituisce false.</span><span class="sxs-lookup"><span data-stu-id="2ae15-105">When the time-out expired, if no tasks were completed or canceled before the method call, but one or more tasks entered these states after the method call, the method returned false.</span></span><br/><br/><span data-ttu-id="2ae15-106">In .NET Framework 4.5 questi overload del metodo ora restituiscono false in presenza di attività ancora in esecuzione allo scadere dell'intervallo di timeout e generano un'eccezione <xref:System.AggregateException?displayProperty=fullName> solo se un'attività di input è stata annullata, indipendentemente dal fatto che sia stata annullata prima o dopo la chiamata del metodo, e non ci sono altre attività ancora in esecuzione.</span><span class="sxs-lookup"><span data-stu-id="2ae15-106">In the .NET Framework 4.5, these method overloads now return false if any tasks are still running when the time-out interval expired, and they throw an <xref:System.AggregateException?displayProperty=fullName> exception only if an input task was cancelled (regardless of whether it was before or after the method call) and no other tasks are still running.</span></span>

#### <a name="suggestion"></a><span data-ttu-id="2ae15-107">Suggerimento</span><span class="sxs-lookup"><span data-stu-id="2ae15-107">Suggestion</span></span>

<span data-ttu-id="2ae15-108">Se veniva rilevata un'eccezione <xref:System.AggregateException?displayProperty=fullName> come mezzo per rilevare un'attività annullata prima della chiamata al metodo <xref:System.Threading.Tasks.Task.WaitAll%2A>, il codice doveva invece eseguire lo stesso rilevamento tramite la proprietà <xref:System.Threading.Tasks.Task.IsCanceled%2A> (ad esempio: .Any(t = &gt; t.IsCanceled)), in quanto in questo caso .NET Framework 4.6 genera un'eccezione solo se tutte le attività attese vengono completate prima del timeout.</span><span class="sxs-lookup"><span data-stu-id="2ae15-108">If an <xref:System.AggregateException?displayProperty=fullName> was being caught as a means of detecting a task that was cancelled prior to the <xref:System.Threading.Tasks.Task.WaitAll%2A> call being invoked, that code should instead do the same detection via the  <xref:System.Threading.Tasks.Task.IsCanceled%2A> property (for example: .Any(t =&gt; t.IsCanceled)) since .NET Framework 4.6 will only throw in that case if all awaited tasks are completed prior to the timeout.</span></span>

| <span data-ttu-id="2ae15-109">Nome</span><span class="sxs-lookup"><span data-stu-id="2ae15-109">Name</span></span>    | <span data-ttu-id="2ae15-110">Valore</span><span class="sxs-lookup"><span data-stu-id="2ae15-110">Value</span></span>       |
|:--------|:------------|
| <span data-ttu-id="2ae15-111">Scope</span><span class="sxs-lookup"><span data-stu-id="2ae15-111">Scope</span></span>   |<span data-ttu-id="2ae15-112">Minorenne</span><span class="sxs-lookup"><span data-stu-id="2ae15-112">Minor</span></span>|
|<span data-ttu-id="2ae15-113">Version</span><span class="sxs-lookup"><span data-stu-id="2ae15-113">Version</span></span>|<span data-ttu-id="2ae15-114">4.5</span><span class="sxs-lookup"><span data-stu-id="2ae15-114">4.5</span></span>|
|<span data-ttu-id="2ae15-115">Type</span><span class="sxs-lookup"><span data-stu-id="2ae15-115">Type</span></span>|<span data-ttu-id="2ae15-116">Runtime</span><span class="sxs-lookup"><span data-stu-id="2ae15-116">Runtime</span></span>

#### <a name="affected-apis"></a><span data-ttu-id="2ae15-117">API interessate</span><span class="sxs-lookup"><span data-stu-id="2ae15-117">Affected APIs</span></span>

-<xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.Int32,System.Threading.CancellationToken)?displayProperty=nameWithType></li><li><xref:System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[],System.TimeSpan)?displayProperty=nameWithType></li></ul>|
